# Generated by Django 4.2.4 on 2023-09-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='desc',
        ),
    ]
