# Generated by Django 4.2.4 on 2023-09-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageweb', '0002_remove_department_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='desc',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='描述信息'),
        ),
    ]
